### PR TITLE
Fix overdue pending mistakes

### PR DESCRIPTION
**Pull request by SooYap**

### CODE REVIEW

**Comment by SooYap** [comment]
Im going to link two issues in this PR because it is a one liner fix and it fixes both #346 and #350.
They both stem from the same problem.

**Review by ghos7ie — CHANGES_REQUESTED** [review]
For context, I am running this on v1.5.1

Can I just check that when a new task is added or when a task is edited, the code does update the status automatically at the execute stage in LogicManager.

image

On further checking, I think the model.setStatus() should be ran before you save the versionHistory.

image

As you can see, while the application shows that the new task I added is overdue, it is not saved as such in addressbook.json

**Comment by SooYap** [comment]
@ghos7ie implemented the changes as discussed. Also implemented deadline null handling for setStatus() so that status will be set to pending when deadline == null. This only happens when the mostRecentTaskDisplay has not been set so everything should be fine.

**Review by ghos7ie — APPROVED** [review]
Looks good, thanks for updating

**Pull request merged**
